image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

services:
  - docker

install:
  - ps: docker-compose up -d
  - sleep 15
  - java -Dspring.datasource.url=jdbc:postgresql://localhost:5432/mypostgre -jar ./artifacts/aqa-shop.jar &

build_script:
  - sleep 10
  - chmod +x gradlew
  - ./gradlew test -Dselenide.headless=true --info  # запускаем тест, флаг --info позволяет выводить больше информации